apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-service
  labels:
    app: visualization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-service
  template:
    metadata:
      labels:
        app: visualization-service
    spec:
      containers:
      - name: visualization-service
        image: visualization-service
        ports:
        - containerPort: 8089
        env:
        - name: PORT
          value: "8089"
        - name: KAFKA_BROKER
          value: "kafka:9092"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "microcommerce"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8089
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
