apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualization-service
  template:
    metadata:
      labels:
        app: visualization-service
    spec:
      containers:
      - name: visualization-service
        image: visualization-service
        ports:
        - containerPort: 8089
        env:
        - name: PORT
          value: "8089"
        - name: KAFKA_BROKER
          value: "kafka:9092"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
